DeleteLostUinApplication:
   Prereg_DeleteLostUinApplication_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplicationResult
      input: '{
	"applicationId": "$ID:CreatePrereg_Valid_Smoke_sid_preRegistrationId$"
}'
      output: '{
"deletedBy": "$IGNORE$"
}'
   Prereg_DeleteLostUinApplication_inValid_preRegistrationId_sid:
      endPoint: /preregistration/v1/applications/prereg/{applicationId}
      role: batch
      restMethod: delete
      inputTemplate: preReg/DeleteLostUinApplication/deleteLostUinApplication
      outputTemplate: preReg/error
      input: '{
	"applicationId": "nhhh654443@@ffffv"
}'
      output: '{
   "errors": [ 
    {
      "errorCode": "PRG_PAM_APP_005",
      "message": "No record found for the requested user id"
    }
  ]
}'