GetApplicationWithPrId:
   Prereg_GetApplicationWithPrId_inValid_preRegistrationId:
      endPoint: /preregistration/v1/applications/{preRegistrationId}
      role: batch
      restMethod: get
      inputTemplate: preReg/GetApplicationWithPrId/getApplicationWithPrId
      outputTemplate: preReg/error
      input: '{
  "preRegistrationId": "dhsb3772@Dfvgbgh"
}'
      output: '{
   "errors": [
    {
      "errorCode": "PRG_APP_013",
      "message": "No Records Found"
    }
  ]
}'