GetApplicationTypes:
   Masterdata_GetApplicationTypes_allValid_smoke:
      endPoint: /v1/masterdata/applicationtypes
      role: admin
      restMethod: get
      inputTemplate: masterdata/GetApplicationTypes/getApplicationTypes
      outputTemplate: masterdata/GetApplicationTypes/getApplicationTypesResult
      input: '{
      
}'
      output: '{
   "errors": null
}'