GetAllApplications:
   Prereg_GetAllApplications_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications
      role: batch
      restMethod: get
      inputTemplate: preReg/GetAllApplications/getAllApplications
      outputTemplate: preReg/GetAllApplications/getAllApplicationsResult
      input: '{
   "type": null
}'
      output: '{
  "errors": null
}'
   Prereg_GetAllApplications_InValid_Type:
      endPoint: /preregistration/v1/applications?type={type}
      role: batch
      restMethod: get
      inputTemplate: preReg/GetAllApplications/getAllApplications
      outputTemplate: preReg/error
      input: '{   
   "type": "erwsdhgqw5dcfbz"
}'
      output: '{
  "errors": [
    {
      "errorCode": "PRG_APP_016",
      "message": "Invalid booking type"
    }
  ]
}'
   Prereg_GetAllApplications_Valid_Type_Smoke_sid:
      endPoint: /preregistration/v1/applications?type={type}
      role: batch
      restMethod: get
      inputTemplate: preReg/GetAllApplications/getAllApplications
      outputTemplate: preReg/GetAllApplications/getAllApplicationsResult
      input: '{
   "type": "NEW_PREREGISTRATION"
}'
      output: '{
  "response": {
     "allApplications":[
        {
           "bookingType": "NEW_PREREGISTRATION"
        }
     ]
  },
  "errors": null
}'